[[plugins]]
repo = 'Lokaltog/vim-easymotion.git'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

# Text
[[plugins]]
repo = 'h1mesuke/vim-alignta.git'

[[plugins]]
repo = 'thinca/vim-template.git'

# Display
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides.git'
hook_post_source = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_indent_levels = 30
    let g:indent_guides_start_level = 2
    let g:indent_guides_guide_size = 1
    let g:indent_guides_space_guides = 1

    let g:indent_guides_auto_colors = 0
    let g:indent_guides_color_change_percent = 20

    augroup indentGuide
        autocmd! indentGuide
        autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd guibg=#191919 ctermbg=6
        autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#303030 ctermbg=0*
    augroup END
'''

# Grep
[[plugins]]
repo = 'thinca/vim-qfreplace.git'

# Syntax Change
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# Syntax
[[plugins]]
repo = 'othree/html5.vim.git'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim.git'

[[plugins]]
repo = 'hail2u/vim-css3-syntax.git'

[[plugins]]
repo = 'hallison/vim-markdown.git'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = 'typescript'

[[plugins]]
kepo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# tags
[[plugins]]
repo = 'jsfaint/gen_tags.vim.git'
hook_source = '''
    let g:gen_tags#ctags_auto_gen = 1
    let g:gen_tags#gtags_auto_gen = 1
'''

# Develop
[[plugins]]
repo = 'sjl/gundo.vim.git'

[[plugins]]
repo = 'thinca/vim-quickrun.git'

[[plugins]]
repo = 'thinca/vim-ref.git'

[[plugins]]
repo = 'jaawerth/nrun.vim.git'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_lint_on_enter = 0
    let g:ale_lint_on_text_changed = 0
    let g:ale_lint_on_filetype_changed = 0
    let g:ale_fix_on_save = 1
    let g:ale_sign_column_always = 1
    let g:ale_fixers = {
    \    'typescript': ['tslint', 'tsserver'],
    \    'javascript': ['eslint'],
    \    'css': ['stylelint'],
    \    'scss': ['stylelint'],
    \}

    " for jsx
    augroup FiletypeGroup
        autocmd!
        au BufNewFile,BufRead *.jsx set filetype=javascript.jsx
    augroup END
    let g:ale_linter_aliases = {'jsx': ['css', 'javascript']}
    let g:ale_linters = {'jsx': ['stylelint', 'eslint']}
'''
